---
swagger: '2.0'
info:
  title: API V1
  version: v1
paths:
  "/posts":
    get:
      summary: list posts
      responses:
        '200':
          description: successful
    post:
      summary: create post
      consumes:
      - application/json
      parameters:
      - name: discussion
        in: body
        required: true
        schema:
          type: object
          properties:
            title:
              type: string
            content:
              type: string
            user:
              properties:
                id:
                  type: string
      responses:
        '201':
          description: successful
  "/posts/{id}":
    parameters:
    - name: id
      in: path
      type: string
      required: true
    get:
      summary: show post
      responses:
        '200':
          description: successful
  "/posts/{id}/comments":
    parameters:
    - name: id
      in: path
      type: string
      required: true
    get:
      summary: show post comments
      responses:
        '200':
          description: successful
  "/users":
    get:
      summary: list users
      responses:
        '200':
          description: successful
    post:
      summary: create user
      consumes:
      - application/json
      parameters:
      - name: user
        in: body
        required: true
        schema:
          type: object
          properties:
            first_name:
              type: string
            last_name:
              type: string
      responses:
        '201':
          description: successful
servers:
- url: http://127.0.0.1:3000/
  variables:
    defaultHost:
      default: 127.0.0.1:3000/
